import { CodeTypeEmitter } from "@typespec/asset-emitter";
import { isErrorModel } from "@typespec/compiler";
import { isHeader, isStatusCode } from "@typespec/http";
import { enumCaseName, escapeIdentifier, internalParamName, isSwiftKeyword } from "./naming.ts";
import { swiftTypeForType } from "./type-mapping.ts";
import type { ResolvedSwiftEmitterOptions } from "./index.ts";

export class SwiftTypeEmitter extends CodeTypeEmitter<ResolvedSwiftEmitterOptions> {
  #modifier(): string {
    return this.emitter.getOptions().accessModifier;
  }

  programContext(_program: any) {
    const sourceFile = this.emitter.createSourceFile("Models.swift");
    return { scope: sourceFile.globalScope };
  }

  sourceFile(sourceFile: any) {
    let contents = "// Code generated by typespec-swift. DO NOT EDIT.\n";
    contents += "// Generated types depend only on the internal HTTPRuntime.\n\n";
    contents += "import Foundation\nimport HTTPRuntime\n\n";
    for (const decl of sourceFile.globalScope.declarations) {
      contents += decl.value + "\n";
    }
    return { path: sourceFile.path, contents };
  }

  modelDeclaration(model: any, name: string) {
    const program = this.emitter.getProgram();
    const modifier = this.#modifier();
    const bodyMembers: any[] = [];
    for (const prop of model.properties.values()) {
      if (isStatusCode(program, prop)) continue; // handled by http-emitter
      if (isHeader(program, prop)) continue; // handled by http-emitter
      bodyMembers.push(prop);
    }

    const protocols = isErrorModel(program, model)
      ? "Codable, Sendable, Hashable, APIError"
      : "Codable, Sendable, Hashable";

    let out = `${modifier} struct ${name}: ${protocols} {\n`;
    for (const prop of bodyMembers) {
      const type = swiftTypeForType(prop.type, program) + (prop.optional ? "?" : "");
      out += `    ${modifier} var ${escapeIdentifier(prop.name)}: ${type}\n`;
    }

    // Memberwise init. Reserved-word members use Swift's dual-name parameter
    // form (`` `protocol` protocolValue: String? ``) so the call-site label is
    // preserved while the body avoids shadowing.
    const params = bodyMembers
      .map((prop) => {
        const type = swiftTypeForType(prop.type, program) + (prop.optional ? "?" : "");
        const label = isSwiftKeyword(prop.name)
          ? `${escapeIdentifier(prop.name)} ${internalParamName(prop.name)}`
          : escapeIdentifier(prop.name);
        return `${label}: ${type}${prop.optional ? " = nil" : ""}`;
      })
      .join(", ");
    out += `\n    ${modifier} init(${params}) {\n`;
    for (const prop of bodyMembers) {
      out += `        self.${escapeIdentifier(prop.name)} = ${internalParamName(prop.name)}\n`;
    }
    out += `    }\n`;
    out += `}\n`;

    return this.emitter.result.declaration(name, out);
  }

  modelInstantiation(model: any, name: string | undefined) {
    // Array<T> and Record<string, V> are mapped to [T] / [String: V] inline by
    // swiftTypeForType() wherever they're referenced as a property type; they
    // must never surface as their own struct declaration.
    if (model.name === "Array" || model.name === "Record") {
      return this.emitter.result.none();
    }
    return super.modelInstantiation(model, name);
  }

  enumDeclaration(en: any, name: string) {
    const modifier = this.#modifier();
    let out = `${modifier} enum ${name}: String, Codable, Sendable, Hashable, CaseIterable {\n`;
    for (const member of en.members.values()) {
      const caseName = escapeIdentifier(enumCaseName(String(member.name)));
      const rawValue = JSON.stringify(String(member.value ?? member.name));
      out += `    case ${caseName} = ${rawValue}\n`;
    }
    out += `}\n`;
    return this.emitter.result.declaration(name, out);
  }

  unionDeclaration(union: any, name: string) {
    const program = this.emitter.getProgram();
    const modifier = this.#modifier();
    const variants = [...union.variants.values()];
    const needsIndirect = variants.some((v: any) => v.type.kind === "Model" || v.type.kind === "Union");
    const kw = needsIndirect ? "indirect enum" : "enum";

    let out = `${modifier} ${kw} ${name}: Codable, Sendable, Hashable {\n`;
    for (const v of variants) {
      const caseName = escapeIdentifier(String(v.name));
      out += `    case ${caseName}(${swiftTypeForType(v.type, program)})\n`;
    }

    // Single-key-object Codable conformance: try each case's key in turn.
    out += `\n    private enum CodingKeys: String, CodingKey {\n`;
    out += `        case ${variants.map((v: any) => escapeIdentifier(String(v.name))).join(", ")}\n`;
    out += `    }\n`;
    out += `\n    ${modifier} init(from decoder: any Decoder) throws {\n`;
    out += `        let container = try decoder.container(keyedBy: CodingKeys.self)\n`;
    for (const v of variants) {
      const caseName = escapeIdentifier(String(v.name));
      const type = swiftTypeForType(v.type, program);
      out += `        if let value = try container.decodeIfPresent(${type}.self, forKey: .${caseName}) {\n`;
      out += `            self = .${caseName}(value)\n`;
      out += `            return\n`;
      out += `        }\n`;
    }
    out += `        throw DecodingError.dataCorrupted(.init(\n`;
    out += `            codingPath: decoder.codingPath,\n`;
    out += `            debugDescription: "No known case key present for ${name}"\n`;
    out += `        ))\n`;
    out += `    }\n`;
    out += `\n    ${modifier} func encode(to encoder: any Encoder) throws {\n`;
    out += `        var container = encoder.container(keyedBy: CodingKeys.self)\n`;
    out += `        switch self {\n`;
    for (const v of variants) {
      const caseName = escapeIdentifier(String(v.name));
      out += `        case .${caseName}(let value): try container.encode(value, forKey: .${caseName})\n`;
    }
    out += `        }\n`;
    out += `    }\n`;
    out += `}\n`;
    return this.emitter.result.declaration(name, out);
  }
}
